/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --include-runtime false` (hash: cfe7d8bb7631f89fc26299278901748c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env {
		SCREENSHOTS: R2Bucket;
		ANALYTICS_DB: D1Database;
		BROWSER: Fetcher;
		ENVIRONMENT: "production";
		APP_ORIGIN: "https://screenshotit.app";
		SESSION_MAX_AGE_SECONDS: "2592000";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "APP_ORIGIN" | "SESSION_MAX_AGE_SECONDS">> {}
}
